### ISSUE TITLE
Handling problem or error?

### ISSUE THREAD

**Issue by omega4h** [HackHerz/pusher#4]
Hi,

I want to test pusher (on debian)  (I'm a FHEM PushNotifier-User, so I know something about this).
Pusher is installed and works. First I started with
pusher --token
After my login (user and pass) I've got a token.
After that I tried (I've defined in PushNotifier some devices):
pusher --list

I've got following error: Some kind of error occured: You need to login first.

How can I do this? With parameters I've to use for a login?

**Comment by HackHerz** [comment]
Did you save the token in /etc/pusher.conf?

**Comment by omega4h** [comment]
There isn't a pusher.conf in /etc.
The reason: as user I'm not allowed to wrote to /etc.
After using "sudo pusher --token" there is a pusher.conf in /etc. After that I can use pusher as normal user.
Thank you!
